Documentation: Document a reliable way how to set the display timeout.
adfinis-sygroup/virtesk pull request #16
Opened 2017-07-05 09:35 UTC by matsimon

This was the easiest way to modify the defaults off, in this case, Fedora 25.

2018-02-24 10:02 UTC, matsimon commented
Forgot to assign this to anyone ;-)

2018-02-24 17:37 UTC, karras requested changes

2018-02-24 17:37 UTC, karras commented on doc/virtesk-tc-tools.rst
> +default values do vary in between disttribution versions thus you might want
s/in between/inbetween/
s/disttribution/distribution

2018-02-24 17:37 UTC, karras commented on doc/virtesk-tc-tools.rst
> +default timeout for screen powerdown may not equal your requirements. - Also
Remove the "-"...

2018-02-24 17:37 UTC, karras commented on doc/virtesk-tc-tools.rst
> +A reliable to customize that timeout is to add the following line in the
s/reliable/reliable way/

2022-06-13 21:26 UTC, karras commented
Project archived

2022-06-13 21:26 UTC, closed without merging